### ISSUE TITLE
rake spec failed: LoadError: cannot load such file -- multi_string_replace/multi_string_replace

### ISSUE THREAD

**Issue by szabgab** [jedld/multi_string_replace#5]
Before trying to configure GitHub Actions, I tried this gem locally in an Ubuntu 22.10 based docker container. `./bin/setup` worked, but `rake spec` failed with the following:

```
/usr/bin/ruby3.0 -I/var/lib/gems/3.0.0/gems/rspec-support-3.8.0/lib:/var/lib/gems/3.0.0/gems/rspec-core-3.8.0/lib /var/lib/gems/3.0.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require "multi_string_replace/multi_string_replace"

LoadError:
  cannot load such file -- multi_string_replace/multi_string_replace
# ./lib/multi_string_replace.rb:2:in `require'
# ./lib/multi_string_replace.rb:2:in `<top (required)>'
# ./spec/spec_helper.rb:2:in `require'
# ./spec/spec_helper.rb:2:in `<top (required)>'


Finished in 0.00018 seconds (files took 0.22099 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00018 seconds (files took 0.22099 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


/usr/bin/ruby3.0 -I/var/lib/gems/3.0.0/gems/rspec-support-3.8.0/lib:/var/lib/gems/3.0.0/gems/rspec-core-3.8.0/lib /var/lib/gems/3.0.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

Have I missed a step setting up the local development environment?

**Comment by jedld** [comment]
You need to run **rake compile** to build the native libraries first

**Comment by szabgab** [comment]
Thanks. that worked.
